python learn.py --dataset KINSHIP `
        --model MSDCSE `
        --regularizer NA `
        --optimizer Adam `
        --rank 400 --k_w 20 --k_h 20 --output_channel 4 `
        --filter_size_list "[(1,3),(1,5),(3,3),(3,3,2),(3,3,3)]" `
        --input_drop 0.30 --hidden_drop 0.15 --feature_map_drop 0.45 `
        --active_fn "selu" --init_fn "kaiming_normal" `
        --use_anchor --use_scale_router `
        --max_neighbors 32 --min_pmi_count 2 `
        --anchor_dropout 0.18 --anchor_pmi_weight 0.12 --anchor_hub_weight 0.02 `
        --anchor_residual_init 0.05 --anchor_gate_bias -2.5 `
        --router_dropout 0.18 --router_temperature 1.10 --router_min_branch_weight 0.03 `
        --router_residual_init 0.05 `
        --ce_weight_source train `
        --learning_rate 0.001 --weight_decay 0.001 `
        --factor 0.5 --patience 8 --min_lr 0.00001 `
        --valid 10 --max_epochs 250 --batch_size 800 `
        --seed 42 --verbose 1 `
        -train -save -id kinship_rasa_cgsr
