python learn.py --dataset WN18RR `
        --model MSDCSE `
        --regularizer NA `
        --optimizer Adam `
        --rank 400 --k_w 20 --k_h 20 --output_channel 4 `
        --filter_size_list "[(1,3),(3,3),(1,5)]" `
        --input_drop 0.30 --hidden_drop 0.20 --feature_map_drop 0.35 `
        --active_fn "selu" --init_fn "kaiming_normal" `
        --use_anchor --use_scale_router `
        --max_neighbors 12 --min_pmi_count 2 `
        --anchor_dropout 0.10 --anchor_pmi_weight 0.20 --anchor_hub_weight 0.08 `
        --anchor_fusion post --module_warmup_epochs 5 --module_ramp_epochs 20 `
        --anchor_residual_init 0.05 --anchor_gate_bias -2.5 `
        --router_dropout 0.10 --router_temperature 0.90 --router_min_branch_weight 0.02 `
        --router_residual_init 0.05 `
        --ce_weight_source train `
        --learning_rate 0.001 --weight_decay 0.0005 `
        --factor 0.5 --patience 5 --min_lr 0.00001 `
        --valid 5 --max_epochs 200 --batch_size 512 `
        --seed 42 --verbose 1 `
        -train -save -id wn18rr_rasa_cgsr
