python learn.py --dataset WN18RR `
        --model MSDCSE `
        --regularizer NA `
        --optimizer Adam `
        --rank 400 --k_w 20 --k_h 20 --output_channel 4 `
        --filter_size_list "[(1,3),(3,3),(1,5)]" `
        --input_drop 0.30 --hidden_drop 0.20 --feature_map_drop 0.35 `
        --active_fn "selu" --init_fn "kaiming_normal" `
        --use_scale_router `
        --router_dropout 0.10 --router_temperature 1.00 --router_min_branch_weight 0.02 `
        --use_rcem `
        --rcem_max_rules 4 --rcem_max_candidates 16 `
        --rcem_min_rule_support 5 --rcem_max_rule_degree 32 `
        --rcem_path_strength 0.05 --rcem_type_strength 0.03 `
        --rcem_path_gate_init 0.03 --rcem_type_gate_init 0.03 `
        --rcem_warmup_epochs 5 --rcem_ramp_epochs 20 `
        --rcem_gate_dropout 0.05 `
        --ce_weight_source train `
        --learning_rate 0.001 --weight_decay 0.0005 `
        --factor 0.5 --patience 5 --min_lr 0.00001 `
        --valid 5 --max_epochs 200 --batch_size 512 `
        --seed 42 --verbose 1 `
        -train -save -id wn18rr_rcem_cgsr
